### PR TITLE
Support EC-230

### LINKED ISSUE #19: TP-Link EC-230
It is a router used from tp-link by providers modified through Agile Config. I was able to use the key to decrypt and it seems to have worked, but I'm having trouble uncompress, it has md5 hash checking error. I'm attaching the conf.bin of this router for your help.

### PR DESCRIPTION
**Pull request by d3dave**
Resolves #19

### CODE REVIEW

**Comment by empctn** [comment]
Thank you very much for your help. Just yesterday I had also managed to adapt the script so that it was possible to check md5 and uncompress from byte 20 onwards. But I'm racking my brain this time in the compression part, I already allowed skiphits like True, as well as in Archers, however for a few bytes the generated file is not the same as the original conf.bin. If you can also see this part of the code (compression) I would appreciate it.

Thanks

**Comment by empctn** [comment]
In the case of this router, it uses 16 bytes of md5 at the beginning and then another 4 bytes that I don't know how are generated by the router. I managed to generate a conf.bin equal to the original only because in this case you know what the 4 bytes are. In order to modify the xml and generate a valid bin, it is necessary to know which 4 bytes come after the 16 bytes of the md5. I generated other conf.bin files on the router page and checked the 4 bytes of each of these bins, they were these:
\x00\x00\x1fw
\x00\x00\x1f#
\x00\x00\x1f&
\x00\x00\x1f~
\x00\x00\x1f\x7f
\x00\x00\x1f2

**Comment by d3dave** [comment]
Hey @empctn, I added packing for EC230. Try running with `--ec230` and see how it goes

**Comment by sta-c0000** [comment]
Thanks very much d3dave, looks great! (and thanks for doing some clean up too! :)
EC-230(-G1) appears to be an ISP customizable version of the Archer C60 (AC1350).  If you don't mind, I'll change it to be more AC1350 generic, hopefully someone with an Archer C60 could confirm and add appropriate HardwareVersion string.  I have no idea how similar the Archer C6 (AC1200) is...

**Comment by d3dave** [comment]
Sure, thanks!

**Pull request merged**
